### ISSUE TITLE
Utilizar as tags semânticas ao invés dos div/class

### ISSUE THREAD

**Issue by fabriciofx** [kamilarochapimentel/DSWI#5]
@kamilarochapimentel Você pode utilizar as tags semânticas ao invés do div/class. Exemplo:

```html
<div class="navegacaoHeader">
            <a href="home.html" >Home</a>
            <a href="missao.html">Missão</a>
            <a href="produtos.html">Produtos</a>
            <a href="servicos.html">Serviços</a>
            <a href="sobre.html">Sobre</a>
 </div>
```

Poderia ser:

```html
<nav>
            <a href="home.html" >Home</a>
            <a href="missao.html">Missão</a>
            <a href="produtos.html">Produtos</a>
            <a href="servicos.html">Serviços</a>
            <a href="sobre.html">Sobre</a>
</nav>
```

E o seu CSS ajustar a tag `<nav>`, assim:

```css
nav a {
         /*tirar o sublinhado*/
        text-decoration: none;
        color: var(--color_blue);
        font-weight: bold;
}
```
